#!/usr/bin/env python
import sys

from rstudio_server_manager import commands, parsers


def main() -> None:
    """Main function that starts the manager."""
    # Parse command line args and show help if none are given
    parser = parsers.get_main_parser()
    args = parser.parse_args([sys.argv[1]] if sys.argv[1:] else ["--help"])

    # Show the help if an invalid command is given
    if args.command is None or not hasattr(commands, args.command):
        print(f"\nunrecognized command: {args.command}\n")
        parser.print_help()
        exit(1)

    # Get the function corresponding to the command and run it with the arguments
    command = getattr(commands, args.command)
    command(sys.argv[2:])


if __name__ == "__main__":
    main()
